version: '3'

services:

  # Pull image react statis dari dockerhub untuk frontend
  surreal-ocean-ui:
    image: j0hanespao/surreal-ocean-ui:latest
    container_name: surreal-ocean-ui
    restart: unless-stopped

  # Pull image actix-web api dari dockerhub untuk api endpoint
  surreal-ocean-api:
    image: j0hanespao/surreal-ocean-api:latest
    # env file tidak ada dalam git repository tapi tersedia
    # di folder yang sama dengan docker-compose pada server
    env_file:
      - .env
    container_name: surreal-ocean-api
    restart: unless-stopped

  # Pull image nginx:alpine-slim
  surreal-ocean-proxy:
    image: nginx:alpine-slim
    # Nginx reverse proxy mendengarkan port 80 dan 443 pada host mesin
    ports:
      - 80:80
      - 443:443
    container_name: surreal-ocean-proxy
    # Bind file nginx.conf, aws-surreal-ocean.crt dan aws-surreal-ocean-priv.key 
    # pada host machine
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/aws-surreal-ocean.crt:/etc/ssl/certs/aws-surreal-ocean.crt
      - ./key/aws-surreal-ocean-priv.key:/etc/ssl/private/aws-surreal-ocean-priv.key