version: '3'

services:

  ui:
    image: j0hanespao/surreal-ocean-ui:latest
    depends_on:
      - nginx
    container_name: surreal-ocean-ui
    restart: unless-stopped
    volumes:
    - surreal-ocean-volume:/ui

  nginx-server:
    image: j0hanespao/surreal-ocean-nginx:latest
    container_name: surreal-ocean-nginx
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped

volumes:
  surreal-ocean-volume: