version: '3'

services:

  ui:
    image: j0hanespao/surreal-ocean-ui:latest

  nginx-server:
    image: j0hanespao/surreal-ocean-nginx:latest
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./ui:/usr/share/nginx/html
