version: '3'

services:

  ui:
    image: j0hanespao/surreal-ocean-ui:latest
    ports:
      "8000:80"
    container_name: sureal-ocean-ui
    restart: unless-stopped
    networks: surreal-ocean-networks

  # api:
  #   image: j0hanespao/surreal-ocean-api:latest
  #   ports:
  #     "11:80"
  #   container_name: surreal-ocean-api
  #   restart: unless-stopped
  #   networks: surreal-ocean-networks

  reverse-proxy:
    image: nginx:alpine-slim
    ports:
      - "80:80"
    container_name: surreal-ocean-proxy
    volumes:
      - /conf:/etc/nginx
      - /cert:/etc/nginx/certs
      - /key:/etc/nginx/private
    networks: surreal-ocean-networks

networks: 
  surreal-ocean-networks: {}