version: '3'

services:

  ui:
    image: j0hanespao/surreal-ocean-ui:latest
    container_name: surreal-ocean-ui

  nginx-server:
    image: nginx:latest
    container_name: surreal-ocean-nginx
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./ui:/usr/share/nginx/html
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert/aws-surreal-ocean.crt:/etc/ssl/certs/aws-surreal-ocean.crt
      - ./cert/aws-surreal-ocean-priv.key:/etc/ssl/private/aws-surreal-ocean-priv.key
