version: '3'

services:

  # Pull image react statis dari dockerhub untuk frontend
  surreal-ocean-ui:
    image: j0hanespao/surreal-ocean-ui:latest
    container_name: surreal-ocean-ui
    restart: unless-stopped

  # api:
  #   image: j0hanespao/surreal-ocean-api:latest
  #   ports:
  #     "11:80"
  #   container_name: surreal-ocean-api
  #   restart: unless-stopped
  #   networks: surreal-ocean-networks

  # Pull image nginx:alpine-slim dan lakukan kostumisasi pada build
  # menggunakan Dockerfile
  surreal-ocean-proxy:
    # Build image nginx sebagai reverse proxy dari Dockerfile
    build:
      context: .
    # Nginx reverse proxy mendengarkan port 80 dan 443 pada host mesin
    ports:
      - "80:80"
      - "443:443"
    container_name: surreal-ocean-proxy