name: Build React UI - Surreal Ocean
on:
  # Workflow di-trigger saat push ke branch dev
  # dan terdapat perubahan pada ui/ saja
  # atau perubahan pada file workflow ini sendiri
  # namun tidak saat terjadi perubahan pada
  # ui/.storybook atau ui/src/stories
  push:
    branches:
      - dev
    paths:
      - "ui/**"
      - ".github/workflows/build-ui.yml"
      - "!ui/.storybook/**"
      - "!ui/src/stories/**"
jobs:
  build-ui-surreal-ocean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositori GitHub
        uses: actions/checkout@v4
      - name: Ekstrak Docker image metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: j0hanespao/surreal-ocean-ui
          tags: |
            type=semver,pattern={{version}},value=v1.0.0
      - name: Login ke DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image dan push ke container repository
        uses: docker/build-push-action@v5
        with:
          context: ./ui
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
